version: '3.1'
services:
  teamspeak:
    image: teamspeak
    depends_on:
      - db
    restart: always
    volumes:
      - ./licensekey.dat:/var/ts3server/licensekey.dat
    ports:
      - 9900-9999:9900-9999/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: ${TS3SERVER_DB_PASSWORD}
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
  db:
    image: mariadb
    restart: always
    volumes:
      - ${VOLUME}/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${TS3SERVER_DB_PASSWORD}
      MYSQL_DATABASE: teamspeak
