name: 'Destroy'

env:
  DIGITALOCEAN_SSH_KEY_NAME: teamspeak-ci
  DIGITALOCEAN_DROPLET_SIZE: s-1vcpu-1gb
  DIGITALOCEAN_REGION: ams3
  DIGITALOCEAN_VOLUME_SIZE: 3GiB

on:
  workflow_dispatch:
    inputs:
      droplet-name:
        description: 'Droplet name teamspeak'
        required: true
        default: "teamspeak"

      droplet-volume:
        description: 'Droplet volume database'
        required: true
        default: "database"

jobs:
  destroy-droplet:
    name: Destroy droplet
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Destroy droplet
        id: destroy-droplet
        continue-on-error: true
        run: |
          doctl compute droplet delete -f ${{ github.event.inputs.droplet-name }}

  destroy-volume:
    name: Destroy volume
    runs-on: ubuntu-latest
    needs:
      - destroy-droplet
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get volume id
        id: get-volume
        run: echo "::set-output name=id::$(doctl compute volume ls --format ID,Name | grep ${{ github.event.inputs.droplet-volume }} | cut -d ' ' -f1)"

      - name: Destroy Volume
        id: destroy-droplet
        run: |
          doctl compute volume delete -f ${{ steps.get-volume.outputs.id }}
